const rules = {
    admin: {
        static: [
            'dashboard-page:visual',
            'clients-section:visual',
            'clients:actions',
            'clients:create',
            'clients:edit',
            'clients:remove',
            'payments-section:visual',
            'clients-page:visual',
            'payments:create',
            'providers-page:visual',
            'providers:list',
            'providers:create',
            'providers:remove',
            'bills:list',
            'bills:create',
            'bills:remove',
            'employies-page:visual',
            'employies-payments:list',
            'employies-payments:create',
            'employies-payments:remove',
            'sellers-page:visual',
            'sellers-payments:list',
            'sellers-payments:create',
            'sellers-payments:remove',
            'employies:list',
            'employies:actions',
            'employies:create',
            'employies:edit',
            'employies:remove',
            'occupations:list',
            'occupations:create',
            'occupations:remove',
            'salaries:list',
            'salaries:create',
            'salaries:remove',
            'sellers:list',
            'sellers:create',
            'sellers:edit',
            'sellers:remove',
            'comission:create',
            'comission:remove',
            'providers:list',
            'providers:create',
            'providers:remove',
            'reports-section:visual',
            'graphics-page:visual',
            'movements-page:visual',
            'reports:list',
            'reports:create',
            'permission-section:visual',
            'accounts-page:visual',
            'accounts:list',
            'accounts:create',
            'accounts:edit',
            'accounts:remove',
            'profiles-page:visual',
            'check'
        ]
    },
    vendedor: {
        static: [
            'dashboard-page:visual',
            'payments-section:visual',
            'sellers-page:visual',
        ]
    },
    cobranza: {
        static: [
            'dashboard-page:visual',
            'clients-section:visual',
            'clients-page:visual',
            'clients:actions',
            'clients:info',
            'payments-section:visual',
            'payments:create'
        ]
    },
    asistente: {
        static: [
            'dashboard-page:visual',
            'clients-section:visual',
            'clients:actions',
            'payments-section:visual',
            'clients-page:visual',
            'providers-page:visual',
            'providers:list',
            'bills:list',
            'employies-page:visual',
            'employies-payments:list',
            'sellers-page:visual',
            'sellers-payments:list',
            'employies:list',
            'occupations:list',
            'salaries:list',
            'sellers:list',
            'providers:list',
            'reports-section:visual',
            'graphics-page:visual',
            'movements-page:visual',
            'reports:list',
            'reports:create',
            'permission-section:visual',
            'accounts-page:visual'
        ]
    }
}

export default rules